### ISSUE TITLE
about demo

### ISSUE THREAD

**Issue by 1191067526** [xb534/SED#11]
i can't run the demo, maybe something is missing，maybe I'm not capable enough, and I hope someone can give me an answer.
![image](https://github.com/xb534/SED/assets/47852514/7d9ce157-6868-4185-b150-f926b82e1df7)
![image](https://github.com/xb534/SED/assets/47852514/ca5d422e-1f7c-4756-b6e1-ec8e7c328b4e)
![image](https://github.com/xb534/SED/assets/47852514/280e78d3-aadd-45ec-966a-f44de8aa7f01)

**Comment by xb534** [comment]
It is a known bug. Just use `add_sed_config`  replace them (`add_cat_seg_config `add_fc_clip_config`).

**Comment by 1191067526** [comment]
Thank you for your reply, but I encountered a new problem. This file seems not to be given? There is also a package for mask_former that I can’t find.
![image](https://github.com/xb534/SED/assets/47852514/b5fd7632-2ff9-4303-8017-8f8c642c208f)
![image](https://github.com/xb534/SED/assets/47852514/03df6280-07d1-4f01-81f4-f1d75faf0f9f)
