### ISSUE TITLE
How to control the gradient back-propagation

### ISSUE THREAD

**Issue by DUT-CSJ** [xb534/SED#13]
Hello, thank you for releasing your great work!
In your paper, some layers' gradient back-propagation is stopped.
I wanna know how to control this process, i.e., where to change it?
Looking forward to your reply!

**Comment by xb534** [comment]
Thank for your attention !
You can refer to the implementation of this [line](https://github.com/xb534/SED/blob/2462f3e223980dca37c003bb9d35e3011be824d1/sed/sed_model.py#L172) of code.

**Comment by DUT-CSJ** [comment]
> Thank for your attention! You can refer to the implementation of this [line](https://github.com/xb534/SED/blob/2462f3e223980dca37c003bb9d35e3011be824d1/sed/sed_model.py#L172) of code.

Learned it, thank you for reply!
