### ISSUE TITLE
compare with cat-seg?

### ISSUE THREAD

**Issue by lchen1019** [xb534/SED#14]
yours:
![image](https://github.com/xb534/SED/assets/87420660/0f5b0d1d-b569-4150-933f-4eb70bc1cdd7)

cat-seg paper:
![image](https://github.com/xb534/SED/assets/87420660/b83ce182-a4af-4d28-8976-879b742f01ad)

Why in your experiment, the effect of cat-seg is much worse than that provided in the cat-seg paper?

**Comment by lchen1019** [comment]
And except for the results of cat-seg, the results you provided are the same as cat-seg.

**Comment by xb534** [comment]
Thank for your attention !
I checked the experimental results from CAT-Seg. The results you provided came from [v2.pdf](https://arxiv.org/pdf/2303.11797v2.pdf), but when I wrote the paper, only  [v1.pdf](https://arxiv.org/pdf/2303.11797v1.pdf)  was available.

**Comment by lchen1019** [comment]
Thank you for your reply. It seems that they made a lot of changes, such as removing the dependency on additional backbones. And their code currently only has the first version.
