### ISSUE TITLE
Training and testing size compared with CAT-Seg

### ISSUE THREAD

**Issue by DUT-CSJ** [xb534/SED#16]
In your experiment settings, your MIN_SIZE_TRAIN and CROP SIZE is bigger than CAT-Seg (768 v.s. 384).
Dose this setting have a big effect on the performance?
Looking forward to your reply!

**Comment by xb534** [comment]
Thank for your attention!
If I recall it correctly，the size of final segmentation mask is the same as that of CAT-Seg.

**Comment by DUT-CSJ** [comment]
Thank you. 
I found CAT-Seg release their CVPR 2024 version which has several changes.
It uses a smaller crop size when training while use sliding window inference.
The feature backbone is removed, all clip model is fine-tuned during training and achieve better results.
