### ISSUE TITLE
关于category templates P

### ISSUE THREAD

**Issue by 21-10-4** [xb534/SED#19]
![image](https://github.com/xb534/SED/assets/91857689/e6a1ddeb-01ab-4381-af6b-e121ad5790eb)
我想知道，为什么能够直接用整套的模板？我的考虑是：假设我的目标类别是鸟。某张图中可能只有一只鸟，而不是有很多只鸟，那么使用 a photo of many birds ，不就不符合实际情况了吗？
我想知道我的理解是不是有问题？非常期待您的回复。

**Comment by xb534** [comment]
实际使用时会存在很多种模板，你举例的这种情况确实存在，但这只代表a photo of many birds这个prompt失效了，但其它prompt对于检测bird这一类还是发挥作用的。这也是为什么使用多个不同的prompt模板，只用某个单一的模板会存在上述问题。
希望这些解答对你有所帮助。

**Comment by zz-2024** [comment]
谢谢(●'◡'●)
