### ISSUE TITLE
Some questions about templates

### ISSUE THREAD

**Issue by wooseok-shin** [xb534/SED#21]
![image](https://github.com/user-attachments/assets/25cbff58-ecc7-4fa7-b0b2-f7625b6046ac)

I am currently performing inference using the provided weights. As shown in the attached image, it seems possible to use multiple options with the "prompt_ensemble_type". However, when I select an argument other than "imagenet," I encounter an error stating that the pretrained weight does not match. As far as I know, the OVSS model should allow inference even if the number of prompts or classes changes dynamically. 
Could you please clarify if there is a reason for this, or if I might be misunderstanding something?

I look forward to your response. Thank you.

**Comment by xb534** [comment]
Thank for your attention. Our SED do not support change the number of prompt templates in the inference stage. You can see this [line code](https://github.com/xb534/SED/blob/main/sed/modeling/transformer/model.py#L579), the prompt number as an hyperparameter when we train the model.

**Comment by wooseok-shin** [comment]
Thank you for the clear explanation.
