### ISSUE TITLE
About Training

### ISSUE THREAD

**Issue by SunQiu88** [xb534/SED#22]
Hello,thanks for your great work！
I find that during training, SEM_SEG_HEAD.POOLING_SIZES is set to [2,2], and during testing, it is set to [1,1]. The purpose of doing this is to improve training efficiency during training, and to help with detailed segmentation and accuracy improvement during testing, Is it correct to understand it this way?

**Comment by xb534** [comment]
Yeah! I think your understanding is correct.

**Comment by SunQiu88** [comment]
@xb534 ,hello,i want to know how to save the best model of the highest mIOU during training ?
