### ISSUE TITLE
代码无法运行

### ISSUE THREAD

**Issue by myhan1996** [xb534/SED#23]
作者您好，您的代码部署之后，无法直接运行，一直报hugging face的网络连接问题。CAT-seg可以。想请教下是什么问题

**Comment by xb534** [comment]
可以尝试在执行程序前设置如下环境变量：export HF_ENDPOINT=https://hf-mirror.com ，使用镜像站下载权重。

**Comment by myhan1996** [comment]
sh run.sh configs/convnextB_768.yaml 4 output/，直接运行这个命令进行训练，会出现报错”AssertionError: Checkpoint output//model_final.pth not found!“。没有在coco上进行训练就直接泛化到其他数据集，是什么问题呢？

**Comment by myhan1996** [comment]
> /data2/users/hanmengya/code/SED/sed/sed_model.py(170)forward()
-> clip_features = self.sem_seg_head.predictor.clip_model.encode_image(clip_images, dense=True)

TypeError: encode_image() got an unexpected keyword argument 'dense'
原因是报这个错误，是什么问题呢

**Comment by zzz-0930** [comment]
> sh run.sh configs/convnextB_768.yaml 4 output/，直接运行这个命令进行训练，会出现报错“AssertionError: Checkpoint output//model_final.pth not found!”。没有在coco上进行训练就直接泛化到其他数据集，是什么问题呢？

佬，这个问题你解决了吗，求教
