### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by myhan1996** [xb534/SED#24]
> clip_features = self.sem_seg_head.predictor.clip_model.encode_image(clip_images, dense=True)

TypeError: encode_image() got an unexpected keyword argument 'dense'

clip_features["clip_vis_dense"]
*** IndexError: too many indices for tensor of dimension 2

**Comment by xb534** [comment]
建议你检查下是否是按照下面的流程安装的clip依赖。
`cd open_clip/`
`make install`
