### ISSUE TITLE
About visualize the results

### ISSUE THREAD

**Issue by Nevaeh7** [xb534/SED#3]
Thanks for your excellent work! Could you please share the code you used to visualize the results in Figure 5 of your paper?

**Comment by xb534** [comment]
[vis.zip](https://github.com/xb534/SED/files/13790881/vis.zip)
This .zip file contains our visualization shell.
Hope it works for you.

**Comment by Nevaeh7** [comment]
> [vis.zip](https://github.com/xb534/SED/files/13790881/vis.zip) This .zip file contains our visualization shell. Hope it works for you.

Thanks for your useful reply
