### ISSUE TITLE
Request for Training Logs for Code Reproduction

### ISSUE THREAD

**Issue by lyhisme** [xb534/SED#4]
I've been exploring your paper and find it incredibly insightful. However, I am unable to fully reproduce the results. Could you please provide the training logs or any relevant information necessary to replicate the training process?

**Comment by xb534** [comment]
Thank you for your attention! I have attached the training logs, hoping it  will assist in solving your issue.

[log.txt](https://github.com/xb534/SED/files/14458806/log.txt)

**Comment by lyhisme** [comment]
> Thank you for your attention! I have attached the training logs, hoping it will assist in solving your issue.
> 
> [log.txt](https://github.com/xb534/SED/files/14458806/log.txt)

Thanks for your reply.
