### ISSUE TITLE
Potential Typo in demo.py Import Statement

### ISSUE THREAD

**Issue by TangentOne** [xb534/SED#5]
While exploring your SED repo, specifically within the demo.py file located at **SED/demo/demo.py**, I encountered a potential issue on line **26**. The code attempts to import a method named `add_mask_former_config`, which, upon review, doesn't appear to be defined within the sed package.

Could it be possible that there's a slight typo in this import statement? I suspect the intended method might actually be `add_sed_config`. 

It would be great if you could verify this and update the code accordingly if needed.

**Comment by xb534** [comment]
After reviewing my local development code, I realized that the file SED/demo/demo.py wasn't used in the demonstration. You can download the necessary file from the attachment in #3 . I will ensure this file is removed in the next commit.

**Comment by TangentOne** [comment]
Thanks for the quick response and for sharing the demo file – much appreciated! 

Also, congrats on acceptance to CVPR'24. Can't wait for the next update!
