### ISSUE TITLE
where is add_cat_seg_config, add_fc_clip_config in demo_for_vis.py

### ISSUE THREAD

**Issue by Ningchuan-Li** [xb534/SED#8]
I am unable to run this script smoothly（demo_for_vis.py）, I can't find these functions “add_cat_seg_config“ and “add_fc_clip_config”  from the entire code.

**Comment by xb534** [comment]
Thank you for your feedback. I have updated the source code accordingly. 
Specifically, I replaced the line of code `from sed import add_cat_seg_config, add_fc_clip_config` with `from sed import add_sed_config`.
